### PR TITLE
fix button loading and bug of form

### LINKED ISSUE #88: Bug: include the loading stating on register button to disable the button
```
<Button disabled={!formState.isValid || loading } variation="primary">
  {loading ? 'Registering...' : 'Register'}
</Button>
```

### PR DESCRIPTION
**Pull request by diegocosta-dev**
resolves #88

### CODE REVIEW

File: src/pages/ChangePassword/index.tsx [hunk 1]
```diff
@@ -19,7 +19,19 @@ const ChangePassword = () => {
...
 
-  const handleInput = (event: ChangeEvent<HTMLInputElement>) => {
+  useEffect(() => {
+    const checkForm = async () => {
+      try {
+        await checkEmailSchema.validate(form);
+        setFormState({ error: '', isValid: true });
+      } catch (err) {
+        setFormState({ error: '', isValid: false });
+      }
```
Comment (davidcostadev) [inline src/pages/ChangePassword/index.tsx:29]: This should be on handleInput function

File: src/pages/Login/index.tsx [hunk 2]
```diff
@@ -27,7 +27,19 @@ const Login = () => {
...
   const history = useHistory();
 
-  const handleInput = (event: ChangeEvent<HTMLInputElement>) => {
+  useEffect(() => {
+    const checkForm = async () => {
+      try {
+        const isValid = await loginSchema.isValid(form);
+        setFormState({ error: { ...initialValues }, isValid: isValid });
+      } catch (err) {
+        setFormState({ error: { ...initialValues }, isValid: false });
```
Comment (davidcostadev) [inline src/pages/Login/index.tsx:36]: Please move this to handleInput

**Review by davidcostadev — CHANGES_REQUESTED** [review]

File: src/pages/ChangePassword/index.tsx [hunk 3]
```diff
@@ -16,17 +16,13 @@ import Text from '../../components/Text';
 
 const ChangePassword = () => {
   const [form, setForm] = useState({ email: '' });
-  const [formState, setFormState] = useState({ error: '', isValid: false });
+  const [formErrors, setFormState] = useState({ error: '' });
```
Comment (davidcostadev) [inline src/pages/ChangePassword/index.tsx:19]: setFormErrors

File: src/pages/Login/index.tsx [hunk 4]
```diff
@@ -22,22 +22,19 @@ const initialValues = {
 };
 
 const Login = () => {
-  const [form, setForm] = useState({ email: '', password: '' });
-  const [formState, setFormState] = useState({ error: initialValues, isValid: false });
   const [userLogin, { loading }] = useMutation(USER_LOGIN);
   const history = useHistory();
 
+  const [form, setForm] = useState(initialValues);
+  const [formErrors, setFormState] = useState({ error: initialValues });
```
Comment (davidcostadev) [inline src/pages/Login/index.tsx:29]: setFormErrors

Comment (davidcostadev) [reply src/pages/Login/index.tsx:29]: and let's use useState(initialValues) instead of useState({ error: initialValues })

File: src/pages/ResetPassword/index.tsx [hunk 5]
```diff
@@ -21,17 +21,13 @@ const initialValues = {
 const ResetPassword = () => {
   const urlQuery = useUrlQuery();
   const [form, setForm] = useState(initialValues);
-  const [formState, setFormState] = useState({ error: initialValues, isValid: false });
+  const [formErrors, setFormState] = useState({ error: initialValues });
```
Comment (davidcostadev) [inline src/pages/ResetPassword/index.tsx:24]: here the same

File: src/pages/SignUp/index.tsx [hunk 6]
```diff
@@ -26,19 +27,16 @@ const initialValues = {
 
 const SignUp = () => {
   const [form, setForm] = useState(initialValues);
-  const [formState, setFormState] = useState({ error: initialValues, isValid: false });
+  const [formErrors, setFormState] = useState({ error: initialValues });
```
Comment (davidcostadev) [inline src/pages/SignUp/index.tsx:30]: here too

File: src/schema/auth.ts [hunk 7]
```diff
@@ -28,7 +28,7 @@ export const registerSchema = yup.object().shape({
 
 export const loginSchema = yup.object().shape({
   email: yup.string().email('Invalid Email!').required('Required'),
-  password: yup.string().required('Required'),
+  password: yup.string().required('Required').min(5, ''),
```
Comment (davidcostadev) [inline src/schema/auth.ts:31]: This min it's not needed

**Review by davidcostadev — CHANGES_REQUESTED** [review]

**Review by davidcostadev — APPROVED** [review]
